Homework-4 (demo)
Ded-Alex-coder/ReactJS pull request #4
Opened 2021-01-27 18:06 UTC by Ded-Alex-coder

Позже доделаю

2021-01-31 09:09 UTC, SokolAlexander commented on Урок 4. Роутинг в React разбиваем мессенджер на чаты/src/components/ChatList.js
> +      <Link className={classes.a} to="/chat/1/">
сделайте массив чатом, рендерьте мапом)

2021-01-31 09:12 UTC, SokolAlexander commented on Урок 4. Роутинг в React разбиваем мессенджер на чаты/src/components/MessageField.js
> +    setInput({ [event.target.name]: event.target.value }); // инпут либо обект с полями либо текстовое поле а у вас и то и другое
"у вас" - это у меняв примере что ли?) используйте строку лучше

2021-01-31 09:12 UTC, SokolAlexander commented on Урок 4. Роутинг в React разбиваем мессенджер на чаты/src/components/MessageField.js
> +          onClick={() => handleSendMessage(input, 'User')}
а чего не хэндл сабмит? опять стрелка в рендере(

2021-01-31 09:16 UTC, SokolAlexander requested changes
В принципе ок, но у вас никак не связаны чаты в стейте мессаджфилд и ссылки на чаты (то есть если я вдруг помещу в стейт мессаджфилд четвертый чат или удалю один из существующих - ссылки будут не соответствовать существующим данным). Рекомендую перенести стейт с сообщениями выше по иерархии и рендерить ссылки на чаты мапом по существующим чатам в стейте. Кроме того, страницы профиля не увидел
Также есть подозрение что все упадет если я введу в адресную строку номер несуществующего чата - рекомендую похэндлить этот кейс через редирект, показывал на одном из уроков

2021-02-01 10:31 UTC, Ded-Alex-coder commented on Урок 4. Роутинг в React разбиваем мессенджер на чаты/src/components/MessageField.js
> +    setInput({ [event.target.name]: event.target.value }); // инпут либо обект с полями либо текстовое поле а у вас и то и другое
Нет. это я попросил помочь наставника. Это его комментарий)

2021-02-01 10:32 UTC, Ded-Alex-coder commented on Урок 4. Роутинг в React разбиваем мессенджер на чаты/src/components/MessageField.js
> +          onClick={() => handleSendMessage(input, 'User')}
Делаю, как в методичке. Все вопросы к ней.

2021-02-24 11:02 UTC, merged